version: '3'
services:
  drupal:
    image: drupal:9-apache
    ports:
      - 8080:80

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: base
      MYSQL_DATABASE: base
      MYSQL_USER: base
      MYSQL_PASSWORD: base
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
